### PR TITLE
Improve display of search results

### PR DESCRIPTION
**Pull request by TheoLeanse**
screen shot 2016-07-22 at 17 48 22
@ookejimift @FTgremlin 
First stab at this - search results are now grouped by vanity & given the colours Anna requested

### CODE REVIEW

**Comment by matthew-andrews** [comment]
how come redirects are red?  they're not bad 😄

**Comment by TheoLeanse** [comment]
it's supposed to be pink!

but i suppose the green/red thing is confusing here

**Comment by matthew-andrews** [comment]
ahh pink

**Comment by TheoLeanse** [comment]
But let's use something else

**Comment by TheoLeanse** [comment]
Something a little more like: 

screen shot 2016-07-25 at 11 26 24

?

**Comment by TheoLeanse** [comment]
or... 

screen shot 2016-07-25 at 11 30 09

**Comment by ookejimift** [comment]
👍  for the first one

**Pull request merged**
