### PR TITLE
Basic url checkability

### PR DESCRIPTION
**Pull request by TheoLeanse**
@matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
struggling to run this locally :/

**Comment by TheoLeanse** [comment]
ah - I need to handle there not being a asset-hashes.json in dev environment

**Comment by TheoLeanse** [comment]
you can work around it (if needs be) by running make build-production

**Comment by matthew-andrews** [comment]
working now :)

**Comment by matthew-andrews** [comment]
yep works for me, nice!

**Comment by matthew-andrews** [comment]
+1

**Comment by TheoLeanse** [comment]
@matthew-andrews 
I've just had a go a fixing that build issue - are there some rules on `require`ing things within functions?

**Comment by matthew-andrews** [comment]
> there some rules on `require`ing things within functions

not rules for a build tool like this,

**Pull request merged**
