### PR TITLE
Let's merge staging into master?

### PR DESCRIPTION
**Pull request by katsuraku**
@FTgremlin this is odd. the comparison seems to show changes but some of the bits that appear as additions are actually already in Master. What do you reckon?

### CODE REVIEW

**Comment by FTgremlin** [comment]
This is using an exceptionally clumsy `npm test` version that we fixed on lantern and nightingale by using a script to start the server _and then_ the test suite.
This is very weird, though:
Example - [line 33](https://github.com/Financial-Times/next-url-management-service/blob/master/client/actions/apiResultsActions.js) on this script says that it's changed in the comparison, but it clearly hasn't.
Is it worth getting master from the server, rebasing locally, and then merging that with staging on a separate branch? That way we can have a fully up-to-date staging before merging with master.

**Comment by katsuraku** [comment]
@FTgremlin Also ayayay some of the builds are still failing for specific commits. Shall we take a look at this as a whole after planning meeting.

**Comment by FTgremlin** [comment]
@katsuraku Si.

**Comment by FTgremlin** [comment]
Let's do this. If this breaks the tool, we can just roll back.

**Comment by FTgremlin** [comment]
giphy-1

**Pull request merged**
